name: Run dockerfile linter
on:
  pull_request:
    paths:
      - "Dockerfile"
      - "./github/workflows/dockerlint.yml"

jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          hadolint_ignore: DL3006 DL3021 DL3059
