name: Build Docker

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/docker.yml'
      - 'Dockerfile'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: ASzc/change-string-case-action@v1
        id: string
        with:
          string: ${{ github.repository_owner }}/discord-spam-reporter
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: ghcr.io/${{ steps.string.outputs.lowercase }}
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: ${{ env.IMAGE_NAME }}:latest